name: Keep Alive

on:
  schedule:
    - cron: '0 12 * * 0'  # 매주 일요일 오후 9시 KST (= UTC 12:00)
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: gautamkrishnar/keepalive-workflow@2.0.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
